FROM 971250452278.dkr.ecr.us-west-1.amazonaws.com/stg-queenmode-base:node-14 as builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM 971250452278.dkr.ecr.us-west-1.amazonaws.com/stg-queenmode-base:node-14-slim
WORKDIR /app
COPY --from=builder /app ./
EXPOSE 3000

CMD ["node", "dist/app"]
